spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
      driver-class-name: org.h2.Driver

  mvc:
    async.request-timeout: 60000

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

com.individual.thinking.traitorstown:
  learning-enabled: false
  learning-steps: 80000
  messaging-enabled: true
  minimum-number-of-players: 4
  maximum-number-of-players: 8
  maximum-number-of-cards: 8

---
# learning
spring:
  profiles: learning
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
    driver-class-name: org.h2.Driver

com.individual.thinking.traitorstown:
  learning-enabled: true
  learning-steps: 40000
  messaging-enabled: false
  minimum-number-of-players: 1
  maximum-number-of-players: 5


logging:
  level:
    com.individual.thinking.traitorstown.game: ERROR

---
# dev
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traitorstown
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

com.individual.thinking.traitorstown:
  minimum-number-of-players: 2
  maximum-number-of-players: 5

---
#production environment
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://traitors-town-db-prod.csah8eocqs8t.eu-west-1.rds.amazonaws.com:3306/traitorstown
    username: traitorstown
    password: cqymgmfJkJqUhNUVyTrALNNLCWSfkKhy
    driver-class-name: com.mysql.jdbc.Driver

