spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username:
      password:
      driver-class-name: org.h2.Driver

  mvc:
    async.request-timeout: 60000

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

---
# learning
spring:
  profiles: learning
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
    driver-class-name: org.h2.Driver

---
# dev
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/traitorstown
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

---
#production environment
spring:
  profiles: production
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

